### PR TITLE
fix: update golang.org/x/net to fix a vulnerability

### PR DESCRIPTION
**Pull request by dkoshkin**
Saw a failure in https://github.com/d2iq-labs/cluster-api-runtime-extensions-nutanix/actions/runs/8555710175/job/23443763742?pr=25, testing if this is enough.

### CODE REVIEW

**Comment by dkoshkin** [comment]
The Go 1.22.2 nix package has not been released yet.

**Review by faiq — APPROVED** [review]

**Comment by faiq** [comment]
does devbox.json need updating?

**Comment by supershal** [comment]
Previous go bump from 1.22.0 to 1.22.1 . Let me see if its easy to file a PR there. https://github.com/NixOS/nixpkgs/commit/33c109bd29ec9e6b948dd25c8897875f7296a402
Meanwhile should we force merge the PRs?

**Comment by supershal** [comment]
https://github.com/NixOS/nixpkgs/pull/301607 :)

**Comment by dkoshkin** [comment]
> [NixOS/nixpkgs#301607](https://github.com/NixOS/nixpkgs/pull/301607) :)

Haha I was coming here to add the link but you beat me to it ❤️

**Pull request closed without merging**
